version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_app
    container_name: laravel_app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=l-chat
      - DB_USERNAME=root
      - DB_PASSWORD=secretbangetcoy
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secretbangetcoy
      MYSQL_DATABASE: l-chat
    volumes:
      - mysql_data:/var/lib/mysql

  node:
    image: node:18
    container_name: laravel_node
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"  # kalo pake vite
    restart: unless-stopped

volumes:
  mysql_data:
